# Dockerfile.jvm-multistage in src/main/docker
FROM maven:3.9.4-eclipse-temurin-21 AS build
WORKDIR /work

# paths relative to the context (project root)
COPY pom.xml .
COPY src src

RUN mvn -DskipTests package -Dquarkus.package.type=uber-jar

FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=build /work/target/*-runner.jar /app/app.jar
EXPOSE 9000 8080
CMD ["java", "-jar", "/app/app.jar"]
